id: P001849
initial_creation_type: ocr
source_metadata:
  id: bdr:W2831
  title: 'ཤུག་གསེབ་རྗེ་བཙུན་སྐུ་ཞབས་ཀྱི་རྣམ་ཐར། '
  author: ''
  volumes:
    4657c0573b9d4092974d4d80e6a163bd:
      image_group_id: I1KG14584
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
