id: P001849
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:47.760615
source_metadata:
  id: bdr:W2831
  title: 'ཤུག་གསེབ་རྗེ་བཙུན་སྐུ་ཞབས་ཀྱི་རྣམ་ཐར། '
  author: ''
  volumes:
    4657c0573b9d4092974d4d80e6a163bd:
      image_group_id: I1KG14584
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
